import 'dart:async';
import 'dart:convert';
import 'dart:developer' as developer;
import 'dart:io';
import 'dart:math';
import 'dart:typed_data';

import 'package:crypto/crypto.dart' show sha256;
import 'package:http/http.dart' as http;

import '../../di/injection.dart';
import 'asset_distribution/installed_asset_store.dart';

/// Outcome of one manifest fetch.
class _FetchResult {
  const _FetchResult(this.manifest, this.etag, {this.unchanged = false});

  final ChordManifest? manifest;
  final String? etag;
  final bool unchanged;
}

/// Result of a chord sync pass against the gyschordweb repository.
class ChordSyncResult {
  const ChordSyncResult({
    required this.downloaded,
    required this.updated,
    required this.skipped,
    required this.failed,
  });

  final int downloaded;
  final int updated;
  final int skipped;
  final int failed;

  bool get changed => downloaded + updated > 0;

  @override
  String toString() =>
      'ChordSyncResult(downloaded: $downloaded, updated: $updated, '
      'skipped: $skipped, failed: $failed)';
}

/// One entry of the SHA-256 chord manifest
/// (`docs/assets-chord-manifest.json` on gyschordweb).
class ChordManifestEntry {
  const ChordManifestEntry({
    required this.id,
    required this.bookCode,
    required this.songNumber,
    required this.title,
    required this.path,
    required this.formatVersion,
    required this.size,
    required this.sha256,
  });

  final String id;
  final String bookCode;
  final String songNumber;
  final String title;
  final String path;
  final int formatVersion;
  final int size;
  final String sha256;

  String get fileName => path.split('/').last;

  factory ChordManifestEntry.fromJson(Map<String, dynamic> json) {
    return ChordManifestEntry(
      id: json['id'] as String? ?? '',
      bookCode: json['bookCode'] as String? ?? '',
      songNumber: json['songNumber'] as String? ?? '',
      title: json['title'] as String? ?? '',
      path: json['path'] as String? ?? '',
      formatVersion: json['formatVersion'] as int? ?? 0,
      size: json['size'] as int? ?? 0,
      sha256: json['sha256'] as String? ?? '',
    );
  }
}

/// Parsed `assets-chord-manifest.json`. Unknown optional fields are ignored
/// so future manifest revisions stay backward compatible as long as the
/// schema version is unchanged.
class ChordManifest {
  const ChordManifest({
    required this.schemaVersion,
    required this.sourceCommit,
    required this.files,
  });

  static const int supportedSchemaVersion = 1;

  final int schemaVersion;
  final String sourceCommit;
  final Map<String, ChordManifestEntry> files; // by id, e.g. "KR:001"

  bool get isSupported => schemaVersion == supportedSchemaVersion;

  factory ChordManifest.fromJson(Map<String, dynamic> json) {
    final rawFiles = json['files'];
    final files = <String, ChordManifestEntry>{};
    if (rawFiles is List<dynamic>) {
      for (final raw in rawFiles) {
        if (raw is! Map<String, dynamic>) continue;
        final entry = ChordManifestEntry.fromJson(raw);
        if (entry.id.isNotEmpty) files[entry.id] = entry;
      }
    }
    return ChordManifest(
      schemaVersion: json['schemaVersion'] as int? ?? 0,
      sourceCommit: json['sourceCommit'] as String? ?? '',
      files: files,
    );
  }

  Map<String, dynamic> toJson() => {
        'schemaVersion': schemaVersion,
        'sourceCommit': sourceCommit,
        'files': [
          for (final entry in files.values)
            {
              'id': entry.id,
              'bookCode': entry.bookCode,
              'songNumber': entry.songNumber,
              'title': entry.title,
              'path': entry.path,
              'formatVersion': entry.formatVersion,
              'size': entry.size,
              'sha256': entry.sha256,
            },
        ],
      };
}

/// Syncs chord JSON files from the gyschordweb repository
/// (github.com/gyspnk/gyschordweb) into the app's support directory.
///
/// The remote `docs/assets-chord-manifest.json` (generated by the repo's CI)
/// carries the SHA-256 of every chord file. This service:
///
///  * fetches the manifest with ETag/`If-None-Match` so unchanged remotes
///    cost a single conditional request,
///  * only downloads entries whose SHA-256 differs from the last known good
///    manifest, always downloading the active song first,
///  * verifies size + SHA-256 + JSON validity before activating a file,
///  * writes through [InstalledAssetStore] (filesystem on native platforms,
///    IndexedDB on web) with atomic file replacement on native,
///  * imports legacy cache files (pre-manifest syncs in `chords/`) that
///    still hash-match instead of re-downloading them,
///  * never prunes or rewrites the cache when the manifest is missing,
///    unsupported, or only partially applied.
class ChordSyncService {
  ChordSyncService(
    this._appDirectory,
    this._http, {
    InstalledAssetStore? installedAssetStore,
  }) : _store = installedAssetStore;

  final AppDirectory _appDirectory;
  final http.Client _http;
  final InstalledAssetStore? _store;

  static const String repoOwner = 'gyspnk';
  static const String repoName = 'gyschordweb';
  static const String defaultBranch = 'main';
  static const String chordDir = 'docs/assets/chord';
  static const String _manifestRepoPath = 'docs/assets-chord-manifest.json';

  static const Duration _timeout = Duration(seconds: 15);
  static const int _maxAttempts = 3;
  static const int _downloadConcurrency = 3;

  static const String _storeRoot = 'chord';
  static const String _stateStorePath = 'chord/sync_state.json';
  static const String _lastManifestStorePath = 'chord/manifest.last.json';

  String get _chordFolder => _appDirectory.chordFolder;
  String get _legacyStatePath => '$_chordFolder/sync_state.json';
  String get _legacyLastManifestPath => '$_chordFolder/manifest.last.json';

  /// The store root as a real filesystem path (native only). Mirrors the
  /// installed-assets layout so readers that need a `File` path can resolve
  /// stored chords directly.
  String get _storeNativeRoot =>
      '${_appDirectory.support}/installed_assets/$_storeRoot';

  Directory get chordDirectory => Directory(_chordFolder);

  Future<ChordSyncResult>? _inFlight;

  String _canonicalStorePath(String bookCode, String number) =>
      '$_storeRoot/$bookCode/$number.chord.json';

  /// Kicks off a sync. Concurrent callers share a single in-flight pass.
  Future<ChordSyncResult> sync({
    String? priorityBookCode,
    String? prioritySongNumber,
  }) {
    final inflight = _inFlight;
    if (inflight != null) return inflight;
    final future = _doSync(
      priorityBookCode: priorityBookCode,
      prioritySongNumber: prioritySongNumber,
    );
    _inFlight = future;
    return future.whenComplete(() => _inFlight = null);
  }

  Future<ChordSyncResult> _doSync({
    String? priorityBookCode,
    String? prioritySongNumber,
  }) async {
    final state = await _readState();
    final fetched = await _fetchManifest(state);
    if (fetched == null) {
      // Network or unsupported schema: keep the cache untouched.
      return const ChordSyncResult(
        downloaded: 0,
        updated: 0,
        skipped: 0,
        failed: 0,
      );
    }
    if (fetched.unchanged) {
      await _touchState(
        etag: state['etag'],
        lastCheck: DateTime.now(),
        lastSuccess: null,
      );
      return const ChordSyncResult(
        downloaded: 0,
        updated: 0,
        skipped: 0,
        failed: 0,
      );
    }

    final manifest = fetched.manifest!;
    if (!manifest.isSupported) {
      developer.log(
        'Chord manifest schema ${manifest.schemaVersion} not supported',
        name: 'ChordSyncService',
      );
      return const ChordSyncResult(
        downloaded: 0,
        updated: 0,
        skipped: 0,
        failed: 0,
      );
    }

    final known = await _readLastManifest();
    final targets = manifest.files.values.toList()
      ..sort((a, b) => a.id.compareTo(b.id));
    if (priorityBookCode != null && prioritySongNumber != null) {
      final priorityId = '$priorityBookCode:$prioritySongNumber';
      final index =
          targets.indexWhere((entry) => entry.id == priorityId);
      if (index > 0) {
        final entry = targets.removeAt(index);
        targets.insert(0, entry);
      }
    }

    var downloaded = 0;
    var updated = 0;
    var skipped = 0;
    var failed = 0;

    final pending = <ChordManifestEntry>[
      for (final entry in targets)
        if (known?.files[entry.id]?.sha256 != entry.sha256) entry,
    ];
    skipped = targets.length - pending.length;

    for (var start = 0;
        start < pending.length && failed == 0;
        start += _downloadConcurrency) {
      final batch = pending.sublist(
        start,
        min(start + _downloadConcurrency, pending.length),
      );
      final results = await Future.wait([
        for (final entry in batch) _downloadAndStore(entry, known),
      ]);
      for (final result in results) {
        if (result == null) {
          failed++;
          continue;
        }
        final wasKnown = known?.files[result.id] != null;
        if (wasKnown) {
          updated++;
        } else {
          downloaded++;
        }
      }
    }

    if (failed > 0) {
      developer.log(
        'Chord sync partially failed: $failed file(s)',
        name: 'ChordSyncService',
      );
      return ChordSyncResult(
        downloaded: downloaded,
        updated: updated,
        skipped: skipped,
        failed: failed,
      );
    }

    // Fully applied: persist the new last-known-good manifest, prune files
    // that no longer exist upstream, and record the success timestamp.
    await _writeLastManifest(manifest);
    final contentChanged = known == null || !_sameContent(known, manifest);
    if (contentChanged) {
      await _prune(manifest);
    }
    await _touchState(
      etag: fetched.etag,
      lastCheck: DateTime.now(),
      lastSuccess: DateTime.now(),
    );
    return ChordSyncResult(
      downloaded: downloaded,
      updated: updated,
      skipped: skipped,
      failed: 0,
    );
  }

  /// Downloads one entry (or imports it from the legacy cache) and stores it
  /// under its canonical path. Returns the entry on success, null on failure.
  Future<ChordManifestEntry?> _downloadAndStore(
    ChordManifestEntry entry,
    ChordManifest? known,
  ) async {
    try {
      // Reuse a legacy cache file when its hash still matches: no download.
      final legacyBytes = await _readLegacyMatching(entry);
      var bytes = legacyBytes;
      if (bytes == null) {
        final response = await _getWithRetry(
          Uri.parse(
            'https://raw.githubusercontent.com/$repoOwner/$repoName/'
            '${entry.path}',
          ),
        );
        if (response == null || response.statusCode != 200) return null;
        bytes = response.bodyBytes;
      }
      if (!_isValidEntry(entry, bytes)) {
        developer.log(
          'Chord verification failed for ${entry.id}',
          name: 'ChordSyncService',
        );
        return null;
      }
      await _writeStored(entry, bytes);
      return entry;
    } catch (e) {
      developer.log(
        'Chord sync failed for ${entry.id}: $e',
        name: 'ChordSyncService',
      );
      return null;
    }
  }

  bool _isValidEntry(ChordManifestEntry entry, List<int> bytes) {
    if (bytes.length != entry.size) return false;
    if (sha256.convert(bytes).toString() != entry.sha256) return false;
    try {
      final decoded = jsonDecode(utf8.decode(bytes));
      if (decoded is! Map<String, dynamic>) return false;
      if (decoded['version'] is! int) return false;
      if (decoded['type'] is! String) return false;
      if (decoded['pages'] is! Map<String, dynamic>) return false;
    } catch (_) {
      return false;
    }
    return true;
  }

  Future<void> _writeStored(ChordManifestEntry entry, List<int> bytes) async {
    final store = _store;
    if (store != null) {
      await store.writeFile(
        _canonicalStorePath(entry.bookCode, entry.songNumber),
        Uint8List.fromList(bytes),
      );
      return;
    }
    final target = File('$_chordFolder/${entry.fileName}');
    await target.parent.create(recursive: true);
    await _atomicWrite(target, bytes);
  }

  /// Finds a legacy (pre-manifest) cache file whose content hash matches the
  /// manifest entry, and migrates it into the active store.
  Future<List<int>?> _readLegacyMatching(ChordManifestEntry entry) async {
    final dir = Directory(_chordFolder);
    if (!await dir.exists()) return null;
    await for (final entity in dir.list()) {
      if (entity is! File || !entity.path.endsWith('.chord.json')) continue;
      final name = entity.uri.pathSegments.last;
      if (!_legacyFileNameMatches(entry, name)) continue;
      try {
        final bytes = await entity.readAsBytes();
        if (sha256.convert(bytes).toString() != entry.sha256) continue;
        if (_store != null) {
          // Keep both until pruning removes the legacy copy.
          await _store.writeFile(
            _canonicalStorePath(entry.bookCode, entry.songNumber),
            Uint8List.fromList(bytes),
          );
        }
        return bytes;
      } catch (_) {
        continue;
      }
    }
    return null;
  }

  bool _legacyFileNameMatches(ChordManifestEntry entry, String name) {
    if (name == entry.fileName) return true;
    final number = entry.songNumber;
    return name.startsWith('$number.') ||
        name.startsWith('${number}_') ||
        name.startsWith('$number-') ||
        name.startsWith('$number ');
  }

  /// Whether two manifests describe the same set of files (ignores
  /// `sourceCommit` and hash changes, which are normal remote updates).
  bool _sameContent(ChordManifest a, ChordManifest b) {
    if (a.files.length != b.files.length) return false;
    return b.files.keys.every(a.files.containsKey);
  }

  /// Deletes cached files whose upstream identity (bookCode:songNumber) no
  /// longer exists in the applied manifest. Only ever called after a fully
  /// successful sync.
  Future<void> _prune(ChordManifest manifest) async {
    final store = _store;
    if (store != null) {
      try {
        for (final path in await store.listFiles(_storeRoot)) {
          if (path.startsWith(_stateStorePath) ||
              path.startsWith(_lastManifestStorePath)) {
            continue;
          }
          // Canonical layout: chord/{book}/{number}.chord.json
          final match = RegExp(r'^chord/([^/]+)/([^/.]+)\.chord\.json$')
              .firstMatch(path);
          if (match != null &&
              !manifest.files.containsKey('${match.group(1)}:${match.group(2)}')) {
            try {
              await store.deleteFile(path);
            } catch (_) {}
          }
        }
      } catch (_) {}
    }

    final dir = Directory(_chordFolder);
    if (!await dir.exists()) return;
    final legacyIds = <String>{
      for (final entry in manifest.files.values) entry.id,
    };
    final legacyNames = <String>{
      for (final entry in manifest.files.values) entry.fileName,
    };
    await for (final entity in dir.list()) {
      if (entity is! File || !entity.path.endsWith('.chord.json')) continue;
      final name = entity.uri.pathSegments.last;
      final number = RegExp(r'^(\d+)').firstMatch(name)?.group(1);
      final id = number == null ? null : 'KR:$number';
      if (legacyNames.contains(name) || legacyIds.contains(id)) continue;
      try {
        await entity.delete();
      } catch (_) {}
    }
  }

  /// Deletes every synced chord file and both manifests so the next sync
  /// re-downloads everything from the repository.
  Future<void> reset() async {
    final store = _store;
    if (store != null) {
      try {
        for (final path in await store.listFiles(_storeRoot)) {
          await store.deleteFile(path);
        }
      } catch (_) {}
    }
    final dir = Directory(_chordFolder);
    if (await dir.exists()) {
      try {
        await dir.delete(recursive: true);
      } catch (_) {}
    }
  }

  /// Resolves the canonical stored chord file for a song, or null when the
  /// sync has not provided it yet. Checks the installed-assets store first,
  /// then the legacy chord folder.
  Future<String?> resolveInstalledChordPathForSong(
    String bookCode,
    String number,
  ) async {
    if (bookCode.isEmpty || number.isEmpty) return null;

    final store = _store;
    if (store != null) {
      final relative = _canonicalStorePath(bookCode, number);
      if (await store.exists(relative)) {
        final path = '$_storeNativeRoot/$bookCode/$number.chord.json';
        if (await File(path).exists()) return path;
      }
    }

    final dir = Directory(_chordFolder);
    if (!await dir.exists()) return null;
    await for (final entity in dir.list()) {
      if (entity is! File || !entity.path.endsWith('.chord.json')) continue;
      final name = entity.uri.pathSegments.last;
      if (name.startsWith('$number.') ||
          name.startsWith('${number}_') ||
          name.startsWith('$number-') ||
          name.startsWith('$number ')) {
        return entity.path;
      }
    }
    return null;
  }

  /// Reads the canonical stored chord bytes for a song (platform-agnostic),
  /// falling back to the legacy folder. Returns null when not synced yet.
  Future<List<int>?> readChordBytes(String bookCode, String number) async {
    final store = _store;
    if (store != null) {
      final bytes =
          await store.readFile(_canonicalStorePath(bookCode, number));
      if (bytes != null) return bytes;
    }
    final path = await resolveInstalledChordPathForSong(bookCode, number);
    if (path == null) return null;
    final file = File(path);
    if (!await file.exists()) return null;
    return file.readAsBytes();
  }

  /// How long ago the last fully-successful sync finished, or null when the
  /// cache has never been synced. Callers use this to throttle background
  /// checks (foreground: ~6h; on-demand for a missing chord: ~5min).
  Future<Duration?> timeSinceLastSync() async {
    final state = await _readState();
    final epoch = state['lastSuccessEpochMs'];
    if (epoch is! int || epoch <= 0) return null;
    return DateTime.now().difference(
      DateTime.fromMillisecondsSinceEpoch(epoch),
    );
  }

  /// Resolves an installed chord file for a song from the legacy folder by
  /// exact basename (the song index writes underscores while gyschordweb
  /// uses spaces), then by song number regardless of title spelling.
  /// Kept for pre-migration caches and existing callers.
  Future<String?> resolveInstalledChordPath(String? chordFile) async {
    if (chordFile == null || chordFile.trim().isEmpty) return null;
    final fileName = chordFile.replaceAll('\\', '/').split('/').last;
    if (!fileName.endsWith('.chord.json')) return null;

    final dir = Directory(_chordFolder);
    if (!await dir.exists()) return null;

    for (final name in {
      fileName,
      fileName.replaceAll('_', ' '),
      fileName.replaceAll(' ', '_'),
    }) {
      final candidate = File('$_chordFolder/$name');
      if (await candidate.exists()) return candidate.path;
    }

    final numberMatch = RegExp(r'(\d+)[._\-]').firstMatch(fileName);
    if (numberMatch != null) {
      final number = numberMatch.group(1)!;
      await for (final entity in dir.list()) {
        if (entity is File && entity.path.endsWith('.chord.json')) {
          final stored = entity.uri.pathSegments.last;
          if (stored.startsWith('$number.') ||
              stored.startsWith('${number}_') ||
              stored.startsWith('$number-')) {
            return entity.path;
          }
        }
      }
    }
    return null;
  }

  // ---- Manifest fetching ---------------------------------------------------

  Future<_FetchResult?> _fetchManifest(Map<String, dynamic> state) async {
    final etag = state['etag'] as String?;
    try {
      final response = await _getWithRetry(
        Uri.parse(
          'https://raw.githubusercontent.com/$repoOwner/$repoName/'
          '$defaultBranch/$_manifestRepoPath',
        ),
        headers: {
          if (etag != null && etag.isNotEmpty) 'If-None-Match': etag,
        },
      );
      if (response == null) return null;
      if (response.statusCode == 304) {
        return _FetchResult(null, etag, unchanged: true);
      }
      if (response.statusCode == 200) {
        final decoded = jsonDecode(utf8.decode(response.bodyBytes));
        if (decoded is! Map<String, dynamic>) return null;
        return _FetchResult(
          ChordManifest.fromJson(decoded),
          response.headers['etag'] ?? response.headers['ETag'],
        );
      }
      if (response.statusCode == 404) {
        // Transition fallback: pre-manifest repository state. The legacy
        // tree-based sync is exercised only while the remote still lacks the
        // manifest; once a manifest-based last-known-good exists the tree
        // fallback is skipped.
        final legacy = await _legacyTreeSync();
        if (legacy == null) return null;
        return _FetchResult(
          _legacyManifestFromTree(legacy),
          null,
        );
      }
      return null;
    } catch (_) {
      return null;
    }
  }

  ChordManifest _legacyManifestFromTree(Map<String, String> tree) {
    final entries = <String, ChordManifestEntry>{};
    for (final entry in tree.entries) {
      final fileName = entry.key;
      final numberMatch = RegExp(r'^(\d+)').firstMatch(fileName);
      final number = numberMatch?.group(1) ?? '';
      final id = 'KR:$number';
      final path = '$chordDir/$fileName';
      entries[id] = ChordManifestEntry(
        id: id,
        bookCode: 'KR',
        songNumber: number,
        title: '',
        path: path,
        formatVersion: 0,
        size: 0,
        sha256: '',
      );
    }
    return ChordManifest(
      schemaVersion: 1,
      sourceCommit: defaultBranch,
      files: entries,
    );
  }

  /// Legacy pre-manifest sync: lists the Git tree via the GitHub API and
  /// downloads every `.chord.json` whose blob SHA differs from the last
  /// tree-synced state. Returns the fetched name->sha map on success.
  Future<Map<String, String>?> _legacyTreeSync() async {
    final response = await _getWithRetry(
      Uri.parse(
        'https://api.github.com/repos/$repoOwner/$repoName/'
        'git/trees/$defaultBranch?recursive=1',
      ),
      headers: const {
        'Accept': 'application/vnd.github+json',
        'User-Agent': 'church-app',
      },
    );
    if (response == null || response.statusCode != 200) return null;
    final body = jsonDecode(response.body) as Map<String, dynamic>;
    final tree = body['tree'] as List<dynamic>? ?? const [];
    final chords = <String, String>{};
    for (final node in tree) {
      final path = (node as Map<String, dynamic>)['path'] as String?;
      final type = node['type'] as String?;
      if (type == 'blob' &&
          path != null &&
          path.startsWith('$chordDir/') &&
          path.endsWith('.chord.json')) {
        chords[path.split('/').last] = node['sha'] as String? ?? '';
      }
    }
    return chords;
  }

  // ---- State persistence ---------------------------------------------------

  Future<Map<String, dynamic>> _readState() async {
    try {
      final store = _store;
      if (store != null) {
        final bytes = await store.readFile(_stateStorePath);
        if (bytes != null) {
          final decoded = jsonDecode(utf8.decode(bytes));
          if (decoded is Map<String, dynamic>) return decoded;
        }
      }
      final file = File(_legacyStatePath);
      if (await file.exists()) {
        final decoded = jsonDecode(await file.readAsString());
        if (decoded is Map<String, dynamic>) return decoded;
      }
    } catch (_) {}
    return {};
  }

  Future<void> _writeState(Map<String, dynamic> state) async {
    final encoded =
        const JsonEncoder.withIndent('  ').convert(state).codeUnits;
    try {
      final store = _store;
      if (store != null) {
        await store.writeFile(_stateStorePath, Uint8List.fromList(encoded));
        return;
      }
      final file = File(_legacyStatePath);
      await file.parent.create(recursive: true);
      await file.writeAsString(
        const JsonEncoder.withIndent('  ').convert(state),
        flush: true,
      );
    } catch (_) {}
  }

  Future<void> _touchState({
    required String? etag,
    required DateTime? lastCheck,
    required DateTime? lastSuccess,
  }) async {
    final state = await _readState();
    if (etag != null) state['etag'] = etag;
    if (lastCheck != null) state['lastCheckEpochMs'] = lastCheck.millisecondsSinceEpoch;
    if (lastSuccess != null) {
      state['lastSuccessEpochMs'] = lastSuccess.millisecondsSinceEpoch;
    }
    await _writeState(state);
  }

  Future<ChordManifest?> _readLastManifest() async {
    try {
      final store = _store;
      if (store != null) {
        final bytes = await store.readFile(_lastManifestStorePath);
        if (bytes != null) {
          final decoded = jsonDecode(utf8.decode(bytes));
          if (decoded is Map<String, dynamic>) {
            return ChordManifest.fromJson(decoded);
          }
        }
      }
      final file = File(_legacyLastManifestPath);
      if (await file.exists()) {
        final decoded = jsonDecode(await file.readAsString());
        if (decoded is Map<String, dynamic>) {
          return ChordManifest.fromJson(decoded);
        }
      }
    } catch (_) {}
    return null;
  }

  Future<void> _writeLastManifest(ChordManifest manifest) async {
    final encoded =
        const JsonEncoder.withIndent('  ').convert(manifest.toJson());
    try {
      final store = _store;
      if (store != null) {
        await store.writeFile(
          _lastManifestStorePath,
          Uint8List.fromList(encoded.codeUnits),
        );
        return;
      }
      final file = File(_legacyLastManifestPath);
      await file.parent.create(recursive: true);
      await file.writeAsString(encoded, flush: true);
    } catch (_) {}
  }

  // ---- HTTP helpers --------------------------------------------------------

  Future<http.Response?> _getWithRetry(
    Uri uri, {
    Map<String, String>? headers,
  }) async {
    for (var attempt = 0; attempt < _maxAttempts; attempt++) {
      try {
        final response = await _http
            .get(uri, headers: headers)
            .timeout(_timeout);
        // 429/5xx are retryable; everything else is final.
        if (response.statusCode == 429 ||
            response.statusCode >= 500 &&
                response.statusCode < 600) {
          await _backoff(attempt);
          continue;
        }
        return response;
      } on TimeoutException {
        await _backoff(attempt);
      } catch (_) {
        await _backoff(attempt);
      }
    }
    return null;
  }

  Future<void> _backoff(int attempt) async {
    if (attempt >= _maxAttempts - 1) return;
    await Future<void>.delayed(
      Duration(milliseconds: 500 * pow(2, attempt).toInt()),
    );
  }

  Future<void> _atomicWrite(File target, List<int> bytes) async {
    final tmp = File(
      '${target.path}.${DateTime.now().microsecondsSinceEpoch}.tmp',
    );
    await tmp.writeAsBytes(bytes, flush: true);
    try {
      await tmp.rename(target.path);
    } catch (_) {
      if (!await target.exists()) rethrow;
      await tmp.delete().catchError((_) => tmp);
    }
  }
}
