org.gradle.jvmargs=-Xmx4G -XX:+HeapDumpOnOutOfMemoryError -Dkotlin.daemon.jvm.options=-Xmx2048M
android.useAndroidX=true
android.enableJetifier=true
kotlin.incremental=false
org.gradle.caching=true
org.gradle.parallel=true
android.builtInKotlin=true

# Only build for arm64-v8a
android.nativeBuild.abiFilters=arm64-v8a

# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
