// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe5JcdxYeLaE1n_aum-TQIkIo5oFdcxo4',
    appId: '1:4071878363:web:43e0ce49a19a5dc4a266fe',
    messagingSenderId: '4071878363',
    projectId: 'hatiku-4c1de',
    authDomain: 'hatiku-4c1de.firebaseapp.com',
    databaseURL: 'https://hatiku-4c1de.firebaseio.com',
    storageBucket: 'hatiku-4c1de.appspot.com',
    measurementId: 'G-09MHH8KMY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwg1W_u1DANHXPuOf3wAwXOWfirhfuhZs',
    appId: '1:4071878363:android:fa4b33575c68ed0ea266fe',
    messagingSenderId: '4071878363',
    projectId: 'hatiku-4c1de',
    databaseURL: 'https://hatiku-4c1de.firebaseio.com',
    storageBucket: 'hatiku-4c1de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcIOWyv9V4H5ToFywYLSxKX1filnOkOhI',
    appId: '1:4071878363:ios:8d1c778bb712122ca266fe',
    messagingSenderId: '4071878363',
    projectId: 'hatiku-4c1de',
    databaseURL: 'https://hatiku-4c1de.firebaseio.com',
    storageBucket: 'hatiku-4c1de.appspot.com',
    androidClientId: '4071878363-49fvamanae3j2vd6921jn9oksdiqes75.apps.googleusercontent.com',
    iosClientId: '4071878363-7a41kf03rqhb80idlht4fisrcmvur8in.apps.googleusercontent.com',
    iosBundleId: 'com.itm.hatiku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcIOWyv9V4H5ToFywYLSxKX1filnOkOhI',
    appId: '1:4071878363:ios:c51e14d5f1a1b62ba266fe',
    messagingSenderId: '4071878363',
    projectId: 'hatiku-4c1de',
    databaseURL: 'https://hatiku-4c1de.firebaseio.com',
    storageBucket: 'hatiku-4c1de.appspot.com',
    androidClientId: '4071878363-49fvamanae3j2vd6921jn9oksdiqes75.apps.googleusercontent.com',
    iosClientId: '4071878363-1psuhe7hkoe7f93sjtiap586p1oe6jga.apps.googleusercontent.com',
    iosBundleId: 'com.itmandiri.church',
  );
}
