## Flutter wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-keep class com.onesignal.flutter.**  { *; }
-keep class com.alveliu.flutterfullpdfviewer.**  { *; }
-keep class com.mr.flutter.plugin.**  { *; }
-keep class com.tekartik.sqflite.**  { *; }
-keep class com.builttoroam.devicecalendar.** { *; }
-keep class androidx.lifecycle.DefaultLifecycleObserver
-keep class com.shockwave.**
-ignorewarnings